Model/src/main/java/org/gusdb/wdk/model/query/SqlQuery.java
As a user of this code, I was very unsatisfied with the following exception:
```
Caused by: org.gusdb.wdk.model.WdkModelException: Database error while attempting to parse sqlQuery DatasetAttributes.All
at org.gusdb.wdk.model.query.SqlQuery.handleColumnTypeException(SqlQuery.java:394)
at org.gusdb.wdk.model.query.SqlQuery.resolveColumnTypes(SqlQuery.java:356)
at org.gusdb.wdk.model.record.RecordClass.assignAttributeFieldDataTypes(RecordClass.java:958)
at org.gusdb.wdk.model.record.RecordClass.resolveAttributeQueryReferences(RecordClass.java:948)
... 12 more
Caused by: java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist
```
because I didn't know where to look for it. After making this change I got the sql, and I was able to see that DatasetAttributes.All is something …
=> Log query in the exception

Model/src/main/java/org/gusdb/wdk/model/query/param/FilterParamNew.java
This is a bit too common in the logs:
```
[18/May/2020|12:56:36] sid:69EE2 rid:  355    9982ms    68.82.218.57 - INFO  - org.gusdb.wdk.model.query.param.FilterParamNew:614 - SELECT count (distinct internal) as cnt FROM (select internal from (SELECT o.*  FROM (select aa.sample_id as internal,
aa.taxon_level_name || ':' || aa.taxon_name as ontology_term_name,
cast(aa.relative_abundance as number) as number_value,
cast(null as date) as date_value,
cast(null as varchar2(1)) as string_value
from 
apidbUserDatasets.UD_AggregatedAbundance aa
where 
aa.user_dataset_id in (17320)
) o) bq WHERE bq.ontology_term_name = ? INTERSECT select internal from ( /* START filteredIdsSql */ /* START filterSelectSql */ SELECT distinct md.internal FROM ( /* START metadataSql */ SELECT o.*  FROM (select …
```
=> Make a common log message into a debug not info

Service/src/main/java/org/gusdb/wdk/service/provider/ExceptionMapper.java
Adds `x-log-marker` header to 500 responses in WdkService.
=> Client error handling

Model/src/main/java/org/gusdb/wdk/core/api/JsonKeys.java, Model/src/main/java/org/gusdb/wdk/model/user/Strategy.java, Service/doc/schema/wdk/includes/strategy-no-step-tree.json, Service/src/main/java/org/gusdb/wdk/service/formatter/StrategyFormatter.java
This PR adds an `isExample` field to the strategy response JSON. The need for this field arises from a recent bug with the "Sort VEuPathDB Example Strategies To Top" checkbox on the client's "Public Strategies" listing. This bug is occurring because the client is hardcoding the name of the example strategies author instead of using the existing `exampleStratsAuthor` model property.
Note: in this implementation, the `isExample` field is derived based on whether the strategy owner's display name matches the `exampleStratsAuthor` model property. During a recent FUT, we realized that in the longer term, it might make sense to have the `exampleStratsAuthor` be the *id* of the example strategy user. That way, we would not have to update `exampleStratsAuthor` whenever the underlying user is …
=> Add "isExample" field to strategy response JSON

Model/src/main/java/org/gusdb/wdk/model/user/dataset/event/datastore/UserDatasetEventDBActions.java
Fixed cleanup_ready event lookup to returning 0 instead of null when no such event was found.
=> Corrected issue causing all iRODS events to be processed each time.

Model/src/main/java/org/gusdb/wdk/cache/CacheMgr.java, Service/src/main/java/org/gusdb/wdk/service/service/TemporaryResultService.java
It occurred to me that we were creating the temporary result with the current session user but then accessing it with some (potentially new) session user, esp if we are passing the URL around to another service that doesn't have the original cookie.  This change will ensure that the result will run as the user who created the temporary result; output should be predictably be as expected.
=> attach user to temporary result

Service/src/main/java/org/gusdb/wdk/service/filter/RequestLoggingFilter.java
At scrum I did not remember why we used a WriterInterceptor to record the end of the request vs a ResponseFilter.  The reason is: a response filter executes at the beginning of the delivery of the response payload, so can be useful in e.g. changing the HTTP response code.  A WriterInterceptor executes only when there is a response body BUT can perform logic at the beginning and/or end of the body-writing process.  Thus, if we want a log line at the VERY end of the request (i.e. after the response has completely been written), we need a WriterInterceptor.  If we want a log line for every request (i.e. those with and without bodies) we need a ResponseFilter.  So, the code here uses both!  I tried to make the verbiage clear about when and what the individual log lines mean.
=> Fixes WDK #30: Improved request completion logging

Model/src/main/java/org/gusdb/wdk/model/user/dataset/event/UserDatasetEventListHandler.java, Model/src/main/java/org/gusdb/wdk/model/user/dataset/event/UserDatasetEventSync.java
Dataset sync script will now run the configured number of events at most per execution.
Subsequent executions of the script will pick up where the previous execution left off and continue processing events.
=> Add hard pagination to the dataset sync script.

Model/src/main/java/org/gusdb/wdk/model/Utilities.java, Model/src/main/java/org/gusdb/wdk/model/record/GenericRecordPrimaryKeyAliasPlugin.java, Model/src/main/java/org/gusdb/wdk/model/record/PrimaryKeyAliasPlugin.java, Model/src/main/java/org/gusdb/wdk/model/record/PrimaryKeyDefinition.java, Model/src/main/java/org/gusdb/wdk/model/record/QueryBasedPrimaryKeyAliasPlugin.java, Model/src/main/java/org/gusdb/wdk/model/record/RecordClass.java
Move alias query logic into a plugin implementation, check for multiple <primaryKey> tags in XML, excluding as necessary, and add a few extra checks.
This is mostly FYI for @aurreco-uga, and window into WDK for @dmgaldi and @Foxcapades
=> Fix up alias query processing

Service/src/main/java/org/gusdb/wdk/service/formatter/UserDatasetFormatter.java
Addresses #43 
Updates to `getAllUserDatasets` so we populate "sharedWith" when listing datasets that the user owns and do not populate the field when listing datasets owned by others.
Possible enhancement would be to avoid use enums instead of booleans to avoid this type of potential mixup.
=> populate sharedWith for my datasets

Model/src/main/java/org/gusdb/wdk/model/answer/AnswerValue.java, Model/src/main/java/org/gusdb/wdk/model/answer/single/SingleRecordAnswerValue.java, Model/src/main/java/org/gusdb/wdk/model/dataset/DatasetContents.java, Model/src/main/java/org/gusdb/wdk/model/dataset/DatasetFactory.java, Model/src/main/java/org/gusdb/wdk/model/dataset/DatasetFileContents.java, Model/src/main/java/org/gusdb/wdk/model/dataset/DatasetListContents.java, Model/src/main/java/org/gusdb/wdk/model/dataset/DatasetStringContents.java, Model/src/main/java/org/gusdb/wdk/model/record/PrimaryKeyIterator.java, Model/src/main/java/org/gusdb/wdk/model/record/ResultSetPrimaryKeyIterator.java, Model/src/main/java/org/gusdb/wdk/model/user/BasketFactory.java, Service/src/main/java/org/gusdb/wdk/service/request/user/dataset/DatasetRequest.java, Service/src/main/java/org/gusdb/wdk/service/request/user/dataset/DatasetRequestProcessor.java, Service/src/main/java/org/gusdb/wdk/service/request/user/dataset/DatasetSourceType.java, Service/src/main/java/org/gusdb/wdk/service/service/user/DatasetService.java
This PR addresses two issues:
1. Dataset upload takes too long because we are allocating only one dataset_value_id at a time from the Oracle sequence. Fix is to allocate a batch of IDs at a time.  How many depends on an estimate of the size of the dataset (or exact match for basket- and step-sourced datasets).
2. AnswerValue has long had two methods that load all IDs of the answer value into memory at one time as a List.  This is problematic for memory and bad practice.  One of the methods could be removed (string processing moved elsewhere); the other was changed to return a closable Iterator<String[]>, which callers can read one PK at a time off of, or concatenate together if they want to live dangerously.
Note this does NOT include the change where basket and strategy results are …
=> Dataset upload fix

Model/src/main/java/org/gusdb/wdk/model/dataset/ListDatasetParser.java
Resolves #47 
Added validation to ListDatasetParser to avoid attempting to search for invalid IDs from junky text files. The regex we came to in the PR is based off discussions with outreach and analysis of existing IDs in the system.
Tested on https://dgaldi.plasmodb.org/plasmo.dgaldi/app/search/transcript/GeneByLocusTag
=> Added validation to ListDatasetParser

Model/src/main/java/org/gusdb/wdk/model/query/ProcessQueryInstance.java, Model/src/main/java/org/gusdb/wdk/model/query/QueryMetric.java, Model/src/main/java/org/gusdb/wdk/model/query/QueryMetrics.java, Model/src/main/java/org/gusdb/wdk/model/query/SqlQueryInstance.java
Log query metrics whenever we run a WDK query to put records in the WDK cache.  If a query is not cacheable (setting in model XML) or is already cached, metrics are not collected.  Note turning off whitespace in the diff will show how little has changed in the ProcessQuery subclasses.
=> Query metrics

Model/src/main/java/org/gusdb/wdk/model/answer/ResultSizeFactory.java, Model/src/main/java/org/gusdb/wdk/model/answer/stream/FileBasedRecordStream.java, Model/src/main/java/org/gusdb/wdk/model/query/SqlQueryInstance.java
it adds 5 single lines in the wdk.log when responding to a request:
HTTP POST /users/current/steps/226875600/reports/standard
(this could help figuring why some requests get hanging using an open connection)
=> add a few log info lines

Model/src/main/java/org/gusdb/wdk/model/query/param/AbstractEnumParam.java, Model/src/main/java/org/gusdb/wdk/model/query/param/FilterParamNewStableValue.java, Model/src/main/java/org/gusdb/wdk/model/query/param/Param.java
This PR addresses two separate issues (combined only for testing convenience):
1. The issue at the bottom of https://redmine.apidb.org/issues/12938, namely for the `refreshed-dependent-params` endpoint to throw 422 instead of 500 in the following instance:
a. Param A is a multi-pick enum param requiring >0 selected terms in a runnable context (but not displayable context)
b. Param B is a filter param (enum would also have this problem) which depends on A and whose vocabulary queries cannot support an empty value (no selected terms) for Param A
c. User clicks "Select None" in Param A, triggering a call to `refreshed-dependent-params` to get the new vocabulary and default value for Param B
2. The issue described in https://redmine.apidb.org/issues/51649, namely that membership filters in …
=> Enum fixes

Model/lib/rng/wdkModel.rng, Model/src/main/java/org/gusdb/wdk/model/BuildTracking.java, Model/src/main/java/org/gusdb/wdk/model/question/Question.java, Model/src/main/java/org/gusdb/wdk/model/report/DynamicAttributeReporterReference.java, Model/src/main/java/org/gusdb/wdk/model/report/ReporterRef.java, Service/doc/schema/wdk/includes/record-reporter.json, Service/src/main/java/org/gusdb/wdk/service/formatter/RecordClassFormatter.java
Enables "standardized" build tracking on reporters.  Thus you can now have model XML like:
```
<reporter name="bed" displayName="(SRT-NEW!) BED - coordinates of sequences, configurable" scopes="results" newBuild="66"
implementation="org.apidb.apicommon.model.report.bed.BedGeneReporter" />
<reporter name="sequence" displayName="(SRT-NEW!) FASTA - sequence retrieval, configurable" scopes="results" newBuild="66"
implementation="org.apidb.apicommon.model.report.sequence.SequenceReporter" />
```
which produces reporter JSON (e.g. at https://rdoherty.plasmodb.org/plasmo.rdoherty/service/record-types/transcript) like:
```
{
"isInReport":true,
"displayName":"(SRT-NEW!) BED - coordinates of sequences, configurable",
"name":"bed",
"description":"(SRT-NEW!) BED - coordinates of sequences, …
```
=> Reporter build tracking

Model/src/main/java/org/gusdb/wdk/core/api/JsonKeys.java, Service/src/main/java/org/gusdb/wdk/service/formatter/param/StringParamFormatter.java
=> Add properties to stringParam response

Model/lib/rng/wdkModel.rng, Model/src/main/java/org/gusdb/wdk/core/api/JsonKeys.java, Model/src/main/java/org/gusdb/wdk/model/ModelXmlParser.java, Model/src/main/java/org/gusdb/wdk/model/record/attribute/AttributeField.java, Model/src/main/java/org/gusdb/wdk/model/record/attribute/DerivedAttributeField.java, Service/src/main/java/org/gusdb/wdk/service/formatter/AttributeFieldFormatter.java
Works with client changes in https://github.com/VEuPathDB/web-monorepo/pull/851 and https://github.com/VEuPathDB/ApiCommonModel/pull/35 to resolve https://github.com/VEuPathDB/web-monorepo/issues/838
=> Add htmlHelp attribute

Model/pom.xml, Model/src/main/java/org/gusdb/wdk/model/fix/VdiMigrationFileReader.java, Model/src/main/java/org/gusdb/wdk/model/fix/table/TableRowUpdater.java, Model/src/main/java/org/gusdb/wdk/model/fix/table/edaanalysis/AnalysisRow.java, Model/src/main/java/org/gusdb/wdk/model/fix/table/edaanalysis/plugins/VDIMigrationPlugin.java, Model/src/test/java/org/gusdb/wdk/model/fix/table/edaanalysis/plugins/VDIMigrationPluginTest.java, Model/src/test/resources/migration-unit-test-1.json
Analysis migration plugin for UDIS -> VDI
Pending VDI deployment to dev
=> Implement analysis migration for VDI

Model/lib/rng/wdkModel.rng, Model/src/main/java/org/gusdb/wdk/core/api/JsonKeys.java, Model/src/main/java/org/gusdb/wdk/model/ModelXmlParser.java, Model/src/main/java/org/gusdb/wdk/model/query/param/Param.java, Model/src/main/java/org/gusdb/wdk/model/query/param/ParamReference.java, Model/src/main/java/org/gusdb/wdk/model/question/Question.java, Service/src/main/java/org/gusdb/wdk/service/formatter/QuestionFormatter.java, Service/src/main/java/org/gusdb/wdk/service/formatter/param/ParamFormatter.java
Resolves https://redmine.apidb.org/issues/53977
Specifically, this request in the comments:
> at UX Apr 3 2024 it was suggested to have the help under the search title, not witin a parameter. This will help understanding the search better.
Depends on client changes from https://github.com/VEuPathDB/web-monorepo/pull/995 and model changes from https://github.com/VEuPathDB/ApiCommonModel/pull/42
**Note**: This also adds a `visibleHelpPosition` attribute to params, which is an older request.
=> Add searchVisibleHelp attribute to questions and visibleHelpPosition to params

Model/src/main/java/org/gusdb/wdk/model/fix/table/edaanalysis/plugins/VDIEntityIdRetriever.java
I mistakenly thought EDA dealt in `internal_abbrev`s instead of `stable_id`s.
=> Fix VDI entity ID retrieval

Model/src/main/java/org/gusdb/wdk/model/fix/table/edaanalysis/plugins/CorrelationRefactorPlugin.java, Model/src/test/java/org/gusdb/wdk/model/fix/table/edaanalysis/plugins/CorrelationRefactorPluginTest.java
* Migration of analyses in refactored correlation plugins.
* Resolves https://github.com/VEuPathDB/service-eda/issues/6
=> Add correlation refactor migration plugin

Model/src/main/java/org/gusdb/wdk/model/report/AbstractAttributeReporter.java, Model/src/main/java/org/gusdb/wdk/model/report/reporter/WordCloudAttributeReporter.java
OOM errors for building giant maps of attribute values by primary key, in memory, where there is no current use case for lookups.
When the reproduceable OOM happens, the attribute value map is holding ~915M of memory across ~2.6 million k/v pairs.  The individual values in this case are comma separated lists of IDs.  
Example Value:
```
PF00630, PF18199, PF18198, PF17857, PF17852, PF13964, PF12781, PF12780, PF12777, PF12775, PF12774, PF08393, PF07646, PF03028, PF01833, PF01344
```
Stream the attribute value query results instead of collecting them into an intermediary map.
Going by code searches performed by Steve, Dave, and I, it appears that the `AbstractAttributeReporter#getAttributeValue` method is only called by `WordCloudAttributeReporter`, and that reporter disregards the keys and …
=> Stream attribute reporter values to avoid OOM errors.

Service/src/main/java/org/gusdb/wdk/service/filter/RequestLoggingFilter.java, Service/src/main/java/org/gusdb/wdk/service/service/AnswerService.java, Service/src/main/java/org/gusdb/wdk/service/service/user/BasketService.java, Service/src/main/java/org/gusdb/wdk/service/service/user/StepService.java
Writes all requests to temporary files, checks sizes and rejects request bodies that are too large.  Then only logs body in service access log if response status code is 5xx, and even then truncates body to a reasonable level.
Possible enhancement would be to check max request size as we are writing to the file to save temp disk space and reject as soon as we go over the limit.  Is it worth it?
=> Request log mem leak

Model/src/main/java/org/gusdb/wdk/model/report/reporter/FullRecordReporter.java, Model/src/main/java/org/gusdb/wdk/model/report/reporter/StandardReporter.java, Model/src/main/java/org/gusdb/wdk/model/report/reporter/XMLReporter.java
WDK table values can sometimes be very large.  Not loading all table rows into memory is a larger fix, but for now we can prevent them from _also_ being copied into a large concatenated string (along with extra formatting chars) before being written to the output stream.  Note this does not work for reporters using table cache but luckily the only reporter using that is gff.
=> Cuts max runtime memory for Strings in table in half
